// <auto-generated />
using DataAccess.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameScore.Repositorio.Migrations
{
    [DbContext(typeof(GameScoreContexto))]
    [Migration("20250406055618_atualizado")]
    partial class atualizado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GameScore.Dominio.Entidades.Jogo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Ativo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Descricao");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Genero");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.HasKey("ID");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("GameScore.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Ativo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Senha");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TipoUsuarioId");

                    b.HasKey("ID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GameScore.Dominio.Entidades.UsuarioJogo", b =>
                {
                    b.Property<int>("UsuarioID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JogoID")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsuarioID", "JogoID");

                    b.HasIndex("JogoID");

                    b.ToTable("UsuarioJogo", (string)null);
                });

            modelBuilder.Entity("GameScore.Dominio.Entidades.UsuarioJogo", b =>
                {
                    b.HasOne("GameScore.Dominio.Entidades.Jogo", "Jogo")
                        .WithMany("UsuarioJogos")
                        .HasForeignKey("JogoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameScore.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("UsuarioJogos")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameScore.Dominio.Entidades.Jogo", b =>
                {
                    b.Navigation("UsuarioJogos");
                });

            modelBuilder.Entity("GameScore.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("UsuarioJogos");
                });
#pragma warning restore 612, 618
        }
    }
}
